server:
  port: 0 # 0?? ????? ?? ???? ??? ?????? ???. (Tomcat started on port 51750 (http) with context path '')
          # ??? ??? ?? ??? ???? ???? status? 1?? ???? ?? ??? ??.

spring:
  application:
    name: user-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true # ??? ????? ?????? ??? ????? ?????? ???? ??. true? ??? ??? ???? ??.
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  # ??? ?????? ???? ??.

  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}}
    # ??? ??? ?? ??? ???? ???? status? 1?? ???? ?? ??? ??. ??? ??? ?? ?? ??.